name: Suggest A Program
description: Anything our community can use to live a better life.
title: Suggest A Program
labels: ["feature :sparkles:", "content :fountain_pen:"]
body:
  - type: markdown
    attributes:
      value: |
        Before submitting this suggestion, be sure to read our [listing policy](https:///the.x3.family/make-positive-impact/contribute/programs)
  - type: markdown
    id: program_info
    attributes:
      value: "## Program info"
  - type: input
    id: program_name
    attributes:
      label: Program Name
    validations:
      required: true
  - type: textarea
    id: program_description
    attributes:
      label: Program Description
    validations:
      required: true
  - type: input
    id: program_live_date
    attributes:
      label: When did the program go live?
      description: We prioritize knowledge, tools, and community programs that are battle-tested
    validations:
      required: true
  - type: textarea
    id: program_where_should_it_live
    attributes:
      label: Who is the most suitable audience?
      description: Be clear about the appropriate framework level and tags for this program. 
    validations:
      required: true
  - type: input
    id: program_author
    attributes:
      label: Who is the author of this program?
      description: We prioritize open source projects when possible
      validations:
        required: true
  - type: input
    id: program_url
    attributes:
      label: Program URL
      description: Please provide a link to the program.
      validations:
        required: true
  - type: textarea
    id: program_additional_context
    attributes:
      label: Additional context
      description: Add any other context or screenshots about the program here
  - type: checkboxes
    id: program_work_on
    attributes:
      label: Would you like to work on this issue?
      options:
        - label: "Yes"
          required: false
        - label: "No"
          required: false
    validations:
      required: true
